### ISSUE TITLE
Major Windows updates continually uninstall the service

### ISSUE THREAD

**Issue by funkydude** [jedisct1/dnscrypt-proxy#312]
After every major Windows update e.g. 8.0 > 8.1, 8.1 > 10, or now, 10 to the new build, the DNSCrypt proxy service will always be removed, leaving people with broken internet connections.

I assume the solution to this would be signing the Windows service, which should be easy now with LetsEncrypt?

**Comment by jedisct1** [comment]
Signing the binaries may solve this. But TLS certificates and Windows Developer certificates are different and incompatible things.

And Letsencrypt will only provide the former. So, this is unlikely to change anytime soon.

**Comment by funkydude** [comment]
It's disappointing that you closed this, as what I stated was not a fact, it was a guess.

The problem here is that DNSCrypt is no longer viable on Windows with this issue, unless you're only installing it on your own machine. I now have to guide people through fixing their internet connections since the new Windows 10 update will break it for them.

Security should not be a hassle, it should be simple and effort free. Unfortunately here the simple and effort free path is telling them to reset back to using their ISPs DNS.

**Comment by jedisct1** [comment]
Are you willing to pay for the certificate?

**Comment by funkydude** [comment]
Before asking that it has to be asked: Are we 100% sure this is the solution to the problem? If so, I'm sure people would be willing to crowdfund/donate. I would.

**Comment by funkydude** [comment]
Here's a cheap one if this is the problem:
https://en.sklep.unizeto.pl/data-safety/code-signing-certificates/open-source-code-signing.html

The company is in the list of Certification Authorities who are members of the Windows Root Certificate Program.

**Comment by bitbeans** [comment]
@funkydude inside this msi are signed files: https://github.com/bitbeans/SimpleDnsCrypt/releases

**Comment by funkydude** [comment]
@bitbeans does it stay after major Windows build updates?

**Comment by bitbeans** [comment]
i have not tested this scenario, but i don`t see any problems

**Comment by funkydude** [comment]
@bitbeans Do you not run Windows 10? It is reproducible by updating to the latest build released this past week.

@jedisct1 What do you think about a 14 euro cert?

**Comment by funkydude** [comment]
@bitbeans Well I'm trying SimpleDNSCrypt in the hopes that the signed service won't be removed. However, my main issue is when I try to use Cisco OpenDNS, then close the application, then open it, it states "Cisco OpenDNS Backwards compatability". This is not the option I selected, and I did not have this issue when performing the basic install as a service.

Also when I tick the box to enable it on my WiFi adaptor (which is disabled in Windows, and marked as red in your UI), the option fails to take effect, and is unticked when I next launch the application.

**Comment by bitbeans** [comment]
@funkydude maybe it`s the wrong project to discuss this :)

> Well I'm trying SimpleDNSCrypt in the hopes that the signed service won't be removed. However, my main issue is when I try to use Cisco OpenDNS, then close the application, then open it, it states "Cisco OpenDNS Backwards compatability". This is not the option I selected, and I did not have this issue when performing the basic install as a service.

fixed in the latest commit (ty).

> Also when I tick the box to enable it on my WiFi adaptor (which is disabled in Windows, and marked as red in your UI), the option fails to take effect, and is unticked when I next launch the application.

fixed in the latest commit (ty).

> Where is the configuration file located? Or is it modifying the registry entries?

There is no configuration file at the moment. The application only needs the dnscrypt-proxy registry entry.

> Another question is why is libsodium installed and run from the temp directory and not in the program files directory?

This is because i use https://github.com/Fody/Costura to merge the assemblies.

**Comment by funkydude** [comment]
Sorry I made the mistake of looking at the DLLs for the GUI application, which doesn't launch when Windows loads anyway, so it doesn't matter that it loads a temp file (assuming it's created every time the GUI launches).

I've updated, thanks, but I have 2 more issues. The following DLLs that are loaded by the proxy service are not compiled with the ASLR flag.
libwinpthread-1.dll
libgcc_s_dw2-1.dll

Fixing that, and assuming Windows won't remove the service since it's signed, I can (hopefully) start recommending DNSCrypt again.

**Comment by funkydude** [comment]
@jedisct1 do you need the 14 euros donated?

@bitbeans do you plan on resolving above issues?

**Comment by funkydude** [comment]
@bitbeans It seems as of 0.2.9 the IP and adaptor issues are resolved. However, the DLLs are still not compiled with ASLR, which is the last remaining (security) issue.

**Comment by funkydude** [comment]
@jedisct1 why is there still no cert?

@jedisct1 @bitbeans ASLR is still a problem in the latest release.

**Comment by bitbeans** [comment]
@funkydude i do not recompile them. i use always the official release version.

**Comment by funkydude** [comment]
@bitbeans @jedisct1 I tried to fetch version info from both DLLs but could not, I just found "build time" with very concerning attributes of `Fri Mar 14 20:17:06 2003` for libgcc_s_dw2-1.dll and `Fri Feb 05 18:21:39 1999` for libwinpthread-1.dll

libsodium correctly has a 2016 date, what's going on?

**Comment by jedisct1** [comment]
It's the gcc runtime library. It has nothing to do with the dnscrypt-proxy source code.

**Comment by funkydude** [comment]
@jedisct1 doesn't answer why you appear to be using an ancient version.

**Comment by jedisct1** [comment]
That's what the latest version on MinGW package in MSYS2 ships with.

**Comment by funkydude** [comment]
@jedisct1 I downloaded from https://msys2.github.io/
It contains a msys-gcc_s-1.dll
It doesn't contain winpthread...

**Comment by jedisct1** [comment]
...then you have to install MinGW.
